compile-pdf:
	pdflatex -jobname=report -quiet -interaction=nonstopmode main.tex > /dev/null 2>&1
	pdflatex -jobname=report -quiet -interaction=nonstopmode main.tex > /dev/null 2>&1

clean:
	@ rm -f *.synctex.gz *.fdb_latexmk *.fls *.aux *.log *.toc